version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: pip
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: pipenv
    directory: "/python"
    schedule:
      interval: "weekly"
